>P1;4S3JA
sequence:4S3JA:::::::0.00: 0.00
FAI-Q-IVT-VRSGD--SVYSL----------ASKYGSTPDEIVK-DNGL
NPAETLVVGQALIVNTKGNNYYVQPGDSLYRISQTYNVPLASLAKVNNLS
LKSILHVGQQLYVPKGTKRSVESIAYLQPSTIPIKESLVNATRAINPFLT
YLAYFSFEAKRDGTLKEPT-ETA--KIANIATQGQTIPM-LVITNIE---
--------NGNFSADLTSVILRDATIQNKFITNILQTAEKYGMRDIHFDF
ESVA---------PEDREAYNRFLRNVKIRLPSG-YTLSTTLVPKTSSNQ
KGKFFEAHDYKAQGQIVDFVVIMTYDWGWQGG---------PPMAISPIG
PVKEVLQYAKSQ-MPPQKIMMGQNLYGFDWKLPFKQ--GNPP--AKAVSS
VAAVALARKYNVPIRYDFT-----AQAPHFNYFDE-----------NGVQ
HEVWFEDARSIQSKFNLMKEQGIGGISYWKIGLPFPQNWRLLVENFT---
-ITKKGEN*

