>P1;5JH8:A
sequence:5JH8:A:::::::0.00: 0.00
A---AMVLA-YYSGYA-GNYAA----------LTRYAASFNAVAV-DFYN
--------------------------------------------------
--------------------------------------------------
--------ITAQGAVTGNG-DPAPNDAISFL-LGRKIPAYGCVSNVDG--
--------NGNWSADIAHAVS--TSAQSQAVANLVKFAQDKRFSGINVDF
EAVA---------QGDRNNFSHFIQVLGRALHAKGLKLIVSVPAFSAKDE
NHPANYGYDLRALGAAADYLQIMSYDEAIPAW---------DPGPVAGSD
WMEDDLDYAVER-VPAAKILNGIPAYGYDWKRPGDG--GML-------YW
KDTQALIARYGAQPRYDAG-----THSLTFNYGAA-----------DGSR
HTVWTENARSVALKASLVNAYGLGGTSLYALGMEDDAFWAAVKQGL----
-----AQR*
