>p1;4icrA
sequence:4icrA:::::::0.00: 0.00
MVLPNFKENLEKYAKLLVANGINVQPGHTLA--LSIDVEQRELAHLIVKEAYALGAHEVIVQWTDDVINREKFLHAPMERL
DNVPEYKIAEMNYLLENKASRLGVRSSDPGALNGVDADKLSASAKAMGLAMKPMRIATQSNKVSWTVAAAAGLEWAKKVFP
NA---------------------ASDEEAVDFLWDQIFKTCRVYEADPVKAWEEHAAILK---------------------
-------SKADMLNKEQFSALHYTAPGTDLTLGLPKNHVWESAGAVNAQGEEFLPNMPTEEVFTAPDFRRADGYVTSTKPLS
YNGNIIEGIKVTFKDGQ--IVDITAEKGDQVMKDLVFENAGARALGECALVPDPSPISQSGITFFNTLFD-DNASNHLAIGA
AYATSVVDGAEMSEEELEAAGLNRSDVHVDFMIGSNQMDIDGIREDGTRVPLFRNGNWAN

>p1;4icrB
sequence:4icrB:::::::0.00: 0.00
MVLPNFKENLEKYAKLLVANGINVQPGHTLA--LSIDVEQRELAHLIVKEAYALGAHEVIVQWTDDVINREKFLHAPMERL
DNVPEYKIAEMNYLLENKASRLGVRSSDPGALNGVDADKLSASAKAMGLAMKPMRIATQSNKVSWTVAAAAGLEWAKKVFPNA
---------------------ASDEEAVDFLWDQIFKTCRVYEADPVKAWEEHAAILK--------------------------
--SKADMLNKEQFSALHYTAPGTDLTLGLPKNHVWESAGAVNAQGEEFLPNMPTEEVFTAPDFRRADGYVTSTKPLSYNGNIIEG
IKVTFKDGQ--IVDITAEKGDQVMKDLVFENAGARALGECALVPDPSPISQSGITFFNTLFD-DNASNHLAIGAAYATSVVDGAE
MSEEELEAAGLNRSDVHVDFMIGSNQMDIDGIREDGTRVPLFRNGNWAN
