>P1;3CZ8A
sequence:3CZ8A:::::::0.00: 0.00
-----MSLSNYIAGTL--SFYVLRNPDLDRELINDYAPYSSSISI-FEYH
--------------------------------------------------
--------------------------------------------------
--------IAPNGDIANQLN-DA--AAIETT-WQRRVTPLATITNLT---
--------SGGFSTEIVHQVLNNPTARTNLVNNIYDLVSTRGYGGVTIDF
EQVS---------AADRDLFTGFLRQLRDRLQAGGYVLTIAVPAKTSD-
NIPWLRGYDYGGIGAVVNYMFIMAYDWHHAGS---------EPGPVAPIT
EIRRTIEFTIAQ-VPSRKIIIGVPLYGYDWIIPYQP--GTVA---SAISN
QNAIERAMRYQAPIQYSAE-----YQSPFFRYSDQ-----------QGRT
HEVWFEGVRSMSRKMQIVREYRLQAIGAWQLTLAEGH-------------
---HHHHH*

