>p1;4icqA
sequence:4icqA:::::::0.00: 0.00
MVLPNFKENLEKYAKLLVANGINVQPGHTLA--LSIDVEQRELAHLIVKE
AYALGAHEVIVQWTDDVINREKFLHAPMERLDNVPEYKIAEMNYLLENKA
SRLGVRSSDPGALNGVDADKLSASAKAMGLAMKPMRIATQSNKVSWTVAA
SRLGVRSSDPGALNGVDADKLSASAKAMGLAMKPMRIATQSNKVSWTVAA
KTCRVYEADPVKAWEEHAAILK----------------------------
SKADMLNKEQFSALHYTAPGTDLTLGLPKNHVWESAGAVNAQGEEFLPNM
PTEEVFTAPDFRRADGYVTSTKPLSYNGNIIEGIKVTFKDGQ--IVDITA
EKGDQVMKDLVFENAGARALGECALVPDPSPISQSGITFFNTLFD-ENAS
NHLAIGAAYATSVVDGAEMSEEELEAAGLNRSDVHVDFMIGSNQMDIDGI
REDGTRVPLFRNGNWAN
>p1;4icqB
sequence:4icqB:::::::0.00: 0.00
MVLPNFKENLEKYAKLLVANGINVQPGHTLA--LSIDVEQRELAHLIVKE
AYALGAHEVIVQWTDDVINREKFLHAPMERLDNVPEYKIAEMNYLLENKA
SRLGVRSSDPGALNGVDADKLSASAKAMGLAMKPMRIATQSNKVSWTVAA
SRLGVRSSDPGALNGVDADKLSASAKAMGLAMKPMRIATQSNKVSWTVAA
KTCRVYEADPVKAWEEHAAILK----------------------------
SKADMLNKEQFSALHYTAPGTDLTLGLPKNHVWESAGAVNAQGEEFLPNM
PTEEVFTAPDFRRADGYVTSTKPLSYNGNIIEGIKVTFKDGQ--IVDITA
EKGDQVMKDLVFENAGARALGECALVPDPSPISQSGITFFNTLFD-ENAS
NHLAIGAAYATSVVDGAEMSEEELEAAGLNRSDVHVDFMIGSNQMDIDGI
REDGTRVPLFRNGNWAN