>P1;3NAP_C
sequence:3NAP_C:::::::0.00: 0.00
SKPLTTIPPTIVVQRPSQYFNNADGVDQGLPLSLKYGNEVILKTPFAGTS
SDE--------------------------------MAL------------
---------------------------EY---------VLKIPNYFSRFK
YSSTS-LPKQVLWTSPVHPQI------------------IRNHVTVVDAP
GQ----------------------------PTLLAYATGFFKYWRGGLVY
TFRFVKTNY--HSGRVQITFHP---FVGYDDVMDSDGKIVRD-------E
YVYRVVVDL--RDQTEATLVVPF----------TSLTPYKVCADVFNSAN
RPKYNYEPRDFKVYDNTTDQFFTGTLCVSALTPLVSSSAVVSSTIDVLVE
VKASDDFEVAVPNTPLWLPVDSLTERPSLDGVPIAQ*