>p1;4icsA
sequence:4icsA:::::::0.00: 0.00
MVLPNFKENLEKYAKLLVANGINVQPGHTLA--LSIDVEQRELAHLIVKEAYALGAHEVIVQWTDDVINREKFLHAPMERLDNVPEYKIAEMNYLLENKA
SRLGVRSSDPGALNGVDADKLSASAKAMGLAMKPMRIATQSNKVSWTVAAAAGLEWAKKVFPNA---------------------ASDEEAVDFLWDQIF
KTCRVYEADPVKAWEEHAAILK----------------------------SKADMLNKEQFSALHYTAPGTDLTLGLPKNHVWESAGAVNAQGEEFLPNM
PTEEVFTAPDFRRADGYVTSTKPLSYNGNIIEGIKVTFKDGQ--IVDITAEKGDQVMKDLVFENAGARALGECALVPDPSPISQSGITFFNTLFD-DNAS
NHLAIGAAYATSVVDGAEMSEEELEAAGLNRSDVHVDFMIGSNQMDIDGIREDGTRVPLFRNGNWAN

>p1;4icsB
sequence:4icsB:::::::0.00: 0.00
MVLPNFKENLEKYAKLLVANGINVQPGHTLA--LSIDVEQRELAHLIVKEAYALGAHEVIVQWTDDVINREKFLHAPMERLDNVPEYKIAEMNYLLENKA
SRLGVRSSDPGALNGVDADKLSASAKAMGLAMKPMRIATQSNKVSWTVAAAAGLEWAKKVFPNA---------------------ASDEEAVDFLWDQIF
KTCRVYEADPVKAWEEHAAILK----------------------------SKADMLNKEQFSALHYTAPGTDLTLGLPKNHVWESAGAVNAQGEEFLPNM
PTEEVFTAPDFRRADGYVTSTKPLSYNGNIIEGIKVTFKDGQ--IVDITAEKGDQVMKDLVFENAGARALGECALVPDPSPISQSGITFFNTLFD-DNAS
NHLAIGAAYATSVVDGAEMSEEELEAAGLNRSDVHVDFMIGSNQMDIDGIREDGTRVPLFRNGNWAN