>p1;5cajA
sequence:5cajA:::::::0.00: 0.00
MGSSHHH---HHHSSGLVPRGSHMLILISPAKTLDYQSPLT-------TT
RYTLP--ELLD------NSQQLIHEAR----KLTPP----QISTLMRISD
KLAGINAA------------------------------------------
-RFHDWQPDFTPANARQAILAFKGDVYTGLQAETFSEDDFDFAQQHLRML
SG-LYGVLRPLDLMQPYRLEMGIRLENARGKDLYQFW-GDIITNKLNEAL
AA---------------------------------------QGDNVVINL
ASDEYFK------------SVKPKKLNAEIIKPVFLDEKNGKFKIISFYA
KKARGLMSRFIIENRLTK------------PEQLTGFNSEGYFFD-EDSS
----------------------------SNG-------------------
-------ELVFKRYEQR

>p1;5cajB
sequence:5cajB:::::::0.00: 0.00
MGSSHHH---HHHSSGLVPRGSHMLILISPAKTLDYQSPLT-------TT
RYTLP--ELLD------NSQQLIHEAR----KLTPP----QISTLMRISD
KLAGINAA------------------------------------------
-RFHDWQPDFTPANARQAILAFKGDVYTGLQAETFSEDDFDFAQQHLRML
SG-LYGVLRPLDLMQPYRLEMGIRLENARGKDLYQFW-GDIITNKLNEAL
AA---------------------------------------QGDNVVINL
ASDEYFK------------SVKPKKLNAEIIKPVFLDEKNGKFKIISFYA
KKARGLMSRFIIENRLTK------------PEQLTGFNSEGYFFD-EDSS
----------------------------SNG-------------------
-------ELVFKRYEQR
