>P1;2ifdA
sequence:2ifdA:::::::0.00: 0.00
--------------------------------------------------
----------------MELIGD----------------------YS----
------KAFLLQTVDGKHQDLKYISPETMVALLTGKFSNIVDKFVIVDCR
YPYEYEGGHIKTAVNLPLE--RDAESFLLKSPIAPCSL--DKRVILIFHC
EFSSERGPRMCRFIRERDLAVNDYPSLYYPEMYILKGGYKEFFPQHP---
NFC-----------------------EPQDYRPMNHEAFKDELKTF----
------------RLKTRSW*