>P1;tseq1
sequence:tseq1:::::::0.00: 0.00
----SNAMAFIQTDTFTLRGYECDAFGRMSIPALMNLMQESANRNAIDYGIGIADLAQKGVGWMLMRFCLRIHQYPRYGDTIQLMTYPTTVDKYFIHRDF
RVLATDGTLLADARSTWLVFSMEKRSMVP-LPDFIRQLSPPANVDPLPALPLKPDFQTASFATAASKSVQVGWLNIDQNQHVNNVAYVQWLLEGVDSEIV
QTREIAEIDLVYRTESHWHDWLSVQSVTETDNSVLHRISQTESGK--------DVLLARSRW-------R*