>P1;1cwrA
sequence:1cwrA:::::::0.00: 0.00
V--------------------------------------------LRSKS
LCHDEIENLLDSDH--RELIGD----------------------YS----
------KAFLLQTVDGKHQDLKYISPETMVALLTGKFSNIVDKFVIVDCR
YPYEYEGGHIKTAVNLPLE--RDAESFLLKSPIAPCSL--DKRVILIFHC
EFSSERGPRMCRFIRERDRAVNDYPSLYYPEMYILKGGYKEFFPQHP---
NFC-----------------------EPQDYRPMNHEAFKDELKTFRLKT
RSWAGERSRRELCSRLQDQ*