>P1;4f67A
sequence:4f67A:::::::0.00: 0.00
MGHHHHHHSHMVKDIIIASFYKFIPLNDFRSLREPILTKMHEIGIKGTII
LAHEGVNGGFAGNREQMNVFYDYLRSDSRFADLHFKETYDNKNPFDKAKV
KLRKEIVTMGVQKVDPSYNAGTYLSPEEWHQFIQD------PNVILLDTR
NDYEYELGTFKNAINPDIENFREFPDYVQRNLIDK--K--DKKIAMF--C
TG-GIRCEKTTAYMKE----------LGFEHVYQLHDGILNYLESIPESE
SLWEGKCFVFDDRVAVDQKLDRVYPQLPQDYKYE----------------
---------------REQK*