>P1;4zwv
sequence:4zwv:::::::0.00: 0.00
-----------------SN--------AMIPLFKVAVSPTALDRVAEVFA
SGYLGQGPRVAEFESALAARLGNPRVVSVHSGTSGLCLALRLLDAPEE--
-----RDEVLSTPLTFEATNWAILADGRRITWVDVDPATLTMDLDDLERK
ISPATRAIIVVHWTGYPVDLDRLAGILDRAEREHGFRPAVIEDCAHAWGA
SYRGVPLGSHGNMCVFSFQALKHLTCGDGGLLTLPGDELHERAMLRRFYG
IDRTADRLRGAYDVAEWGLKWHMTDLNAAIGLANLETVDEQLRLHRENAA
FYDKELTGVPGLELLQRSPDREGSFYVYDVKVDDRPAFHRKMEAAGIMAG
LVSRRNDEHSCVAHLRTSLPGLDSVYDRMVSLPVGWWLTEQDREHVVATI
RSGW*