>P1;3NAP_B
sequence:3NAP_B:::::::0.00: 0.00
----------------------------L---AVNNVNMKQMNVNSSQDT
TFE--------------------------------QRS------------
---------------------------QEKVQAGEINESIEFRNQITTFV
HDNPIITEQ-LIGD-SPQPSGDVRSVSDARTHSIIDFLERPQFIGSFLWN
TSDIENKEIFSLKLPDALMSPM------IREKL----SG-FTSFSASTVF
HIQVNAHPFQCGRLVLAAVPVPDILPLHRLNMLS---------FDVSNVI
TLPHVQLDI--SKETEVLLKIPYVSPFVQYDLVTKFTPWAAFLAHVYAPL
NTPSAASLQV-----------------------------------NVFA-
--HFEDIKLGF-------PT----------SAIVAQ*