>P1;3NAP_A
sequence:3NAP_A:::::::0.00: 0.00
VG-FA-------------------SAG-TRDIRSSYVEGKFIPQDITGMS
RNHELDEQPSQECIGERILSFSELIKRNSWRYVSDEKSLIYPAYAFDNPA
AMYTAADKLPVWTLTPRSGFPTLLTSIGA---------MY------AFYR
GGIRL----KIVPGVADQPKPLVEVALFT-MQDQGYIIKANDYSTDFCS-
--------------------SNIYENFVTKGIAE-----VQTPYYSRVNT
SVVSAPVLYNAGNISPLMPNVMYKITSNSSNIL-----LGHSAADDFRFG
FLLGAPLAISATALRDNFTG------------------------SSATVS
LPTFSNFY------------------------------------------
---------------------LS------STSESTT*