>P1;4Q6TA
sequence:4Q6TA:::::::0.00: 0.00
SNAAPFVLA-YTDGQVEASYSN----------LQAFHRNLSAVGLGSTYG
--------------------------------------------------
--------------------------------------------------
--------LTVTGKLRQDGMNETTQNIIRFA-KSQSLPLYPTVSDYNE--
-------DIGAFDPAISHSILNDRALSAGTVKQLVKLAKEGGFAGINLDF
EKVE---------PRNRAAFCAFVKTLGNALHASNKKLIISIPPKLSDTE
-PEYLQGYDYKALGAAVDYFQVMTYDQVGPGWSSGGFHNEAWPGPESGFD
WQQALLSYAVSR-VPASKVLAGLPTYGQDYSIGN-----RV-------HW
SAYQEIIAEHRAAIHRDAA-----SATPYATWGPVKSFVDGVEWTPERAQ
PVLWYDDAASIKTKTALVTRLGLGGTSVWAMGYENAGFWAALQSGLKASN
ELLPTGRE*
