>P1;4WIWA
sequence:4WIWA:::::::0.00: 0.00
SNA-KISLQ-YWDGYA--SYET----------YLRQLSLIPGKAT-DYVD
YVS-----------------------------------------------
--------------------------------------------------
--------PNWRGSIGTDG-------SLKLV-WDEGSSNYKQLTNMAHGL
GMKVLPLING--SGATLNTLLKSPAAREKLIGEIVVLLKNTNADGVVIDF
ETPLDYGDVKDPYDGVRNDLTAFMESLHSELQSMNKLVVMAVMPRMSS--
SQYWLDAYDYEALSHAVDYLHVMTYDHHYRTS---------APGPIAPYP
WIKQVLTYIQGQGVDMSKVLMGIPYYGRDWVVDGKDANGNPTYNSTAFGY
SKALELADSYGATITYSKYNDADPVGTPTFKYTDE-----------KGVE
HTVFFDDYTSWNAKLSIINEFGLAGVGPWAMGWVDENTAEGLFPLL----
---NQHLR*

